export const navHeight = "4rem"
export const tithelyScript = "https://tithe.ly/widget/v3/give.js?3"
export const connectCardLabel = "Connect Card"
export const connectFormLink = "https://wpcc.church/forms/connect"
export const toolsLink = "https://wpcc.church/tools"
export const talksLink = "https://wpcc.church/talks"
export const prayerFormLink = "https://wpcc.church/forms/prayer"
const youtubeBase = "https://www.youtube.com/embed/videoseries?list="
export const youtubeLink = youtubeBase + "PLJbXzmMjnMZJ0BdXS3pT0qXblBCrj4Gip"
export const bibleReading = "bible/111/ISA.10.NIV"
